package:
  name: conda_lockfile
  version: "0.1"

channels:
- defaults

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyyaml

test:
  requires:
    - pytest
  imports:
    - conda_lockfile.cli
  commands:
    - pytest --pyargs conda_lockfile
