dist: trusty
language: rust
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx

install:
  - sh ci/install.sh

script:
  - bash ci/script.sh

deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
