version: 2.1

commands:
  run_install_and_script:
    steps:
      - run: ./ci/install.sh
      - run: ./ci/script.sh

jobs:
  unit_test_linux:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run_install_and_script 

  unit_test_darwin:
    macos:
      xcode: 16.2.0
    steps:
      - checkout
      - run_install_and_script

  deploy_linux:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      # needs ANACONDA_ORG_TOKEN env var
      - run_install_and_script
      - run: ./ci/deploy.sh

  deploy_darwin:
    macos:
      xcode: 16.2.0
    steps:
      - checkout
      # needs ANACONDA_ORG_TOKEN env var
      - run_install_and_script
      - run: ./ci/deploy.sh

workflows:
  run_ci:
    jobs:
      - unit_test_linux:
          filters:
            tags:
              only: /release_.*/
      - unit_test_darwin:
          filters:
            tags:
              only: /release_.*/
      - deploy_linux:
          requires:
            - unit_test_linux
          filters:
            tags:
              only: /release_.*/
            branches:
              ignore: /.*/
      - deploy_darwin:
          requires:
            - unit_test_darwin
          filters:
            tags:
              only: /release_.*/
            branches:
              ignore: /.*/

