version: 2.1

orbs: 
  rust: circleci/rust@1.6.0

jobs:
  unit_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: ./ci/install.sh
      - run: ./ci/script.sh

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      # needs ANACONDA_ORG_TOKEN env var
      - run: ./install.sh
      - run: ./script.sh
      - run: ./deploy.sh

workflows:
  run_ci:
    jobs:
      - rust/unit_test
      - deploy:
          requires:
            - unit_test
          filters:
            tags:
              only: /release_.*/
            branches:
              ignore: /.*/
