version: 2

jobs:
  unit_test:
    docker:
      - image: circleci/python:3-jessie-node-browsers
    environment:
      MINICONDA_VERSION: "Miniconda3-4.5.4-Linux-x86_64.sh"

    steps:
      - checkout
      - run: wget https://repo.continuum.io/miniconda/$MINICONDA_VERSION
      - run: bash $MINICONDA_VERSION -b -f -p $HOME/miniconda
      - run:
          name: Run tests
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            python setup.py test

  mypy:
    docker:
      - image: circleci/python:3-jessie-node-browsers
    steps:
      - run: sudo pip install mypy
      - checkout
      - run: mypy conda_lockfile

  conda_build:
    docker:
      - image: circleci/python:3-jessie-node-browsers
    environment:
      MINICONDA_VERSION: "Miniconda3-4.5.4-Linux-x86_64.sh"

    steps:
      - checkout
      - run: wget https://repo.continuum.io/miniconda/$MINICONDA_VERSION
      - run: bash $MINICONDA_VERSION -b -f -p $HOME/miniconda
      - run:
          name: Build conda packages
          command: | 
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda install -y conda-build
            conda build .


workflows:
  version: 2
  run_ci:
    jobs:
      - unit_test
      - mypy
      - conda_build
