version: 2

jobs:
  unit_test:
    docker:
      - image: conda/miniconda3

    steps:
      - checkout
      - run: python setup.py test

  mypy:
    docker:
      - image: circleci/python:3-jessie-node-browsers
    steps:
      - run: sudo pip install mypy
      - checkout
      - run: mypy conda_lockfile

  conda_build:
    docker:
      - image: conda/miniconda3

    steps:
      - checkout
      - run: conda install -y conda-build
      - run: conda build .

  push_anaconda_org:
    docker:
      - image: conda/miniconda3

    steps:
      - run: conda install -y anaconda-client
      - run: anaconda login --username $(CONDA_USER) --password $(CONDA_PASS)
      - run: conda build . --output | xargs anaconda upload



workflows:
  version: 2
  run_ci:
    jobs:
      - unit_test
      - mypy
      - conda_build
